### ISSUE TITLE
[게임 - 혼자하기] 땅 좌표 가져오기

### ISSUE THREAD

**Issue by sangyeon3** [boostcampwm-2022/iOS08_Acha#35]
## 📌 할 일
- [x] 실제 좌표 따오기
- [x] 데이터베이스에 저장

**Comment by seungki-cho** [comment]
두 구역에 대한 좌표 추가했습니다.
1. workspace
2. 부평동초등학교

![Image](https://user-images.githubusercontent.com/57134892/201807256-a36775dd-19b5-4f1a-9b2e-604a9908d2c1.png)
